# Retrieve data from datawarehouse table

This is a very short example on how to retrieve data from the datawarehouse without to an pandas dataframe, without using an sql query.

The export_data function is a wrapper with some simple functionality and could be further extended if needed. It does not allow to query multiple tables or to run merges/joins/aggregations etc. But you can just load your necessary data into multiple dataframes and run all analysis in python. Or run those commands immediatly in sql.

A user guide and the general pandas documentaion can be found [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html).

---

To discover the data in the datawarehouse you can either use the [DW Table Explorer](https://reports.ad.iea.org/reports/powerbi/IEA%20databases) or use a tool like Microsoft SQL Server Management Studio to connect to the datawarehouse and run queries. It can be downloaded via the Software Center. To connect use the following settings:
- Server type: Database Engine
- Server name: dw.ad.iea.org,14330
- Authentication: Windows Authentication

In [ ]:
# Import function from riselib
from riselib.dw import export_data

In [ ]:
# Check the documentation for the function
help(export_data)

Help on function export_data in module riselib.dw:

export_data(table: str, database: str, columns: list = None, conditions: dict = None, return_query_string: bool = False, limit: int = None) -> pandas.core.frame.DataFrame
    Get Data from IEA Data Warehouse.

    This function exports data from a specified database table from the IEA data warehouse. It allows some additional
    functionality and is a simple wrapper for the actual sql query.

    Args:
    ----
    table (str): The name of the table from which to export data.
    database (str): The name of the database where the table is located.
    columns (list, optional): A list of column names to be included in the output. If not provided, all columns are
        included.
    conditions (dict, optional): A dictionary where the keys are column names and the values are conditions for
        filtering the data. #todo right now only supports equality and exists in list conditions
    return_query_string (bool, optional): If True, the function will return the SQL query string instead of executing
        the query. Useful for debugging.
    limit (int, optional): The maximum number of rows to return. If not provided, all rows are returned.

    Returns:
    -------
    df (pd.DataFrame): A DataFrame containing the exported data.
    or
    query_string (str): The SQL query string, if return_query_string is True.

In [ ]:
# Only query the first 10 rows to get a quick overview
export_data('ele.V_ELECTRICITY_GENERATION_SIMPLE_FUEL_HOURLY', 'Division_EDC', limit=10)

,Country,Code Country,ISO3,Region,Source,Product,Fuels,Renewables,Fuel Category,Flow 1,...,Code Month,Day,Hour,Generation GW,Min Value,Max Value,Ocurrences,event date,Weekday,updated_at
0,Austria,AUSTRIA,AUT,None,Entso-e,Hydro Run-of-river,Hydro,Renewables,Hydro,None,...,6,16,23,3.487750,3468.00000,3499.000000,4,2022-06-16,5,2023-06-06 07:32:05.280
1,Poland,POLAND,POL,None,Entso-e,Coal,Coal,Non-Renewables,Combustible Fuels,None,...,6,16,21,0.079000,79.00000,79.000000,1,2017-06-16,6,2021-02-07 06:41:31.757
2,Australia,AUSTRALI,AUS,New South Wales,AEMO NEM,Solar,Solar,Renewables,Variable Renewables,None,...,3,10,7,0.028953,0.00000,117.162756,12,2020-03-10,3,2023-12-05 07:34:48.203
3,Australia,AUSTRALI,AUS,Queensland,AEMO NEM,Natural Gas,Natural Gas,Non-Renewables,Combustible Fuels,None,...,3,5,16,0.589334,575.99214,619.547590,12,2018-03-05,2,2021-05-12 08:03:54.833
4,Italy,ITALY,ITA,None,Entso-e,Hydro Pumped Storage,Hydro,Renewables,Hydro,None,...,7,20,2,-0.506000,-506.00000,-506.000000,1,2019-07-20,7,2021-02-02 07:19:22.740
5,United States,USA,USA,New York,EIA,Wind Onshore,Wind,Renewables,Variable Renewables,None,...,9,5,3,0.164000,164.00000,164.000000,1,2021-09-05,1,2021-09-06 06:51:36.007
6,Japan,JAPAN,JPN,Chugoku,Energia,Biomass,Biomass/Waste,Renewables,Combustible Renewables,None,...,1,25,6,0.187000,187.00000,187.000000,1,2023-01-25,4,2023-02-23 07:31:19.363
7,Bolivia,Bolivia,BOL,None,CNDC.bo,Thermal,Thermal,Non-Renewables,Combustible Fuels,None,...,1,17,9,0.516500,516.50000,516.500000,1,2016-01-17,1,2021-04-22 08:45:14.557
8,Peru,PERU,PER,None,coes.pe,Solar,Solar,Renewables,Variable Renewables,None,...,5,3,20,0.216200,208.80000,223.600000,2,2022-05-03,3,2022-05-05 07:32:13.660
9,Portugal,PORTUGAL,PRT,None,Entso-e,Hard Coal,Coal,Non-Renewables,Combustible Fuels,None,...,6,23,16,1.744000,1744.00000,1744.000000,1,2015-06-23,3,2021-02-06 06:43:56.330

In [ ]:
# Get all generation data for Ukraine
export_data('ele.V_ELECTRICITY_GENERATION_SIMPLE_FUEL_HOURLY', 'Division_EDC', conditions={'ISO3': ['UKR']})

,Country,Code Country,ISO3,Region,Source,Product,Fuels,Renewables,Fuel Category,Flow 1,...,Code Month,Day,Hour,Generation GW,Min Value,Max Value,Ocurrences,event date,Weekday,updated_at
0,Ukraine,UKRAINE,UKR,None,Entso-e,Hard Coal,Coal,Non-Renewables,Combustible Fuels,None,...,9,28,10,5.473,5473.0,5473.0,1,2021-09-28,3,2023-06-06 07:32:05.280
1,Ukraine,UKRAINE,UKR,None,UKRENERGO,Natural Gas,Natural Gas,Non-Renewables,Combustible Fuels,None,...,2,4,4,1.139,1139.0,1139.0,1,2018-02-04,1,2022-05-19 07:32:41.863
2,Ukraine,UKRAINE,UKR,None,Entso-e,Other,Other combustibles,Non-Renewables,Combustible Fuels,None,...,11,25,21,0.033,33.0,33.0,1,2021-11-25,5,2021-11-26 06:37:08.773
3,Ukraine,UKRAINE,UKR,None,UKRENERGO,Nuclear,Nuclear,Non-Renewables,Nuclear,None,...,9,3,3,8.048,8048.0,8048.0,1,2017-09-03,1,2022-05-19 07:32:41.863
4,Ukraine,UKRAINE,UKR,None,Entso-e,Hydro Pumped Storage,Hydro,Renewables,Hydro,None,...,10,1,7,0.000,0.0,0.0,1,2021-10-01,6,2022-01-05 06:30:45.833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448362,Ukraine,UKRAINE,UKR,None,UKRENERGO,Hydro Pumped Storage,Hydro,Renewables,Hydro,None,...,8,22,5,-0.759,-759.0,-759.0,1,2019-08-22,5,2022-05-19 07:32:41.863
448363,Ukraine,UKRAINE,UKR,None,UKRENERGO,Nuclear,Nuclear,Non-Renewables,Nuclear,None,...,1,23,9,10.131,10131.0,10131.0,1,2018-01-23,3,2022-05-19 07:32:41.863
448364,Ukraine,UKRAINE,UKR,None,Entso-e,Other,Other combustibles,Non-Renewables,Combustible Fuels,None,...,11,20,10,0.026,26.0,26.0,1,2021-11-20,7,2021-11-21 06:35:01.867
448365,Ukraine,UKRAINE,UKR,None,UKRENERGO,Other Renewables,Other renewables,Renewables,Other Renewables,None,...,6,19,22,0.023,23.0,23.0,1,2017-06-19,2,2022-05-19 07:32:41.863
448366,Ukraine,UKRAINE,UKR,None,UKRENERGO,Hydro,Hydro,Renewables,Hydro,None,...,10,18,20,2.645,2645.0,2645.0,1,2016-10-18,3,2022-05-19 07:32:41.863